/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_FlightSystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import negocio.EventosN;

/**
 *
 * @author jossava
 * @author JONATHAN
 */
public class Eventos extends javax.swing.JFrame {

    EventosN eventosNegocio;
    ResultSet rs;
    
    MenuPrincipal mP;
    
    /**
     * Constructor
     */
    public Eventos(Connection conexion, MenuPrincipal mp) {
        initComponents();
        eventosNegocio = new EventosN(conexion);
        rs=null;
        
        mP = mp;
        limpiarCampos();
        cargarSucursalesEnCbx();
        
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblubicaciones = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jTextFieldCosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblubicaciones.setFont(new java.awt.Font("L M Roman Demi10", 1, 48)); // NOI18N
        lblubicaciones.setForeground(new java.awt.Color(1, 1, 1));
        lblubicaciones.setText("Evento");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarbtnAgregarActionPerformed(evt);
            }
        });

        jTextFieldNombre.setEditable(false);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Identificación", "Sucursal", "Nombre Evento", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Identificación:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nombre del Evento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Sucursal");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - -" }));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarbtnBuscarActionPerformed(evt);
            }
        });

        jTextFieldID.setEditable(false);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButtonAtras.setMaximumSize(new java.awt.Dimension(50, 40));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(50, 40));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(58, 34));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jTextFieldCosto.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Costo Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(471, 471, 471)
                        .addComponent(lblubicaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCosto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblubicaciones)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCosto)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarbtnAgregarActionPerformed
        if(validarQueSePuedeGuardar()){
            String name = jTextFieldNombre.getText();
            String costo = jTextFieldCosto.getText();
            String suc = jComboBox1.getSelectedItem().toString();

            if (eventosNegocio.insert(suc, name, costo )) {
                JOptionPane.showMessageDialog(null, "Se ha insertado el Evento.");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo insertar el Evento.");
            }

            actualizar();
            limpiarCampos();
        }
    }//GEN-LAST:event_jButtonAgregarbtnAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        jComboBox1.setSelectedIndex(0);
        if(jTextFieldID.isEditable() && !jTextFieldNombre.isEditable() && !jTextFieldCosto.isEditable()){
            String identificacion=jTextFieldID.getText();
            if(identificacion.equals("") ){
                JOptionPane.showMessageDialog(null, "No hay Evento por eliminar o faltan datos.");
                return;
            }else{
                if(eventosNegocio.delete(identificacion)){
                    actualizar();
                    JOptionPane.showMessageDialog(null, "Se ha eliminado el Evento.");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el Evento."+'\n'
                        + "Puede estar intentando borrar un dato que no se puede eliminar"+'\n'
                        + "debido a que otro registro en otra tabla depende de él.");
                }
            }
        }else{
            jTextFieldID.setEditable(true);
            jTextFieldNombre.setText("");
            jTextFieldNombre.setEditable(false);
            jTextFieldCosto.setEditable(false);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        if(jTextFieldID.isEditable() && jTextFieldNombre.isEditable() && jTextFieldCosto.isEditable()){
            String id_evento=jTextFieldID.getText();
            String name = jTextFieldNombre.getText();
            String costo = jTextFieldCosto.getText();
            String suc = jComboBox1.getSelectedItem().toString();
            if(id_evento.equals("") || name.equals("") || costo.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan datos.");
                return;
            }
            if(jComboBox1.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Seleccione la Sucursal");
                return;
            }
            String tipocontr = jComboBox1.getSelectedItem().toString();
            if (eventosNegocio.update(id_evento, suc, name, costo)) {
                actualizar();
                JOptionPane.showMessageDialog(null, "Se ha modificado el Evento");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el Evento");
            }

        }else{
            jTextFieldID.setEditable(true);
            jTextFieldNombre.setEditable(true);
            return;
        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBuscarbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarbtnBuscarActionPerformed
        if(validarQueSePuedeBuscar()){
            if(!jTextFieldID.isEditable() && !jTextFieldNombre.getText().equals("")){
                rs=eventosNegocio.retrieve(jTextFieldNombre.getText());
                actualizarTabla(rs);
            }
        }
    }//GEN-LAST:event_jButtonBuscarbtnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        mP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel lblubicaciones;
    // End of variables declaration//GEN-END:variables

    public void limpiarCampos() {
        jTextFieldID.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCosto.setText("");
        jTextFieldID.setText("");
        jTextFieldNombre.setText("");
        jTextFieldCosto.setText("");
        jTextFieldID.setEditable(false);
        jTextFieldNombre.setEditable(false);
        jTextFieldCosto.setEditable(false);
        jComboBox1.setSelectedIndex(0);
        actualizar();
    }
    
    public void actualizar(){
        rs=eventosNegocio.getDataSet();
        actualizarTabla(rs);
    }
    
    public void actualizarTabla(ResultSet rs){
        try{
            cleanJTable();
            int i = 0;
            while (rs.next()) {
                jTable1.setValueAt(rs.getString(1), i, 0);   
                jTable1.setValueAt(rs.getString(2), i, 1);                   
                jTable1.setValueAt(rs.getString(3), i, 2);
                jTable1.setValueAt(rs.getString(4), i, 3);
                i++;
            }
            if(i==0)
                JOptionPane.showMessageDialog(null, "No hay datos por mostrar."); 

        }catch(SQLException se) {
            se.printStackTrace();
        }
    }
    
    public void cleanJTable(){
        for(int i=0 ; i<jTable1.getRowCount() ; i++){
            for(int j=0 ; j<jTable1.getColumnCount() ; j++){
                jTable1.setValueAt("", i, j);
            }
        }
    }

    public boolean validarQueSePuedeBuscar(){
        jComboBox1.setSelectedIndex(0);
        if(jTextFieldID.isEditable()){
            jTextFieldID.setText("");
            jTextFieldID.setEditable(false);
            return false;
        }
        if(!jTextFieldNombre.isEditable()){
            jTextFieldNombre.setEditable(true);
            return false;
        }
        
        if(jTextFieldCosto.isEditable()){
            jTextFieldCosto.setText("");
            jTextFieldCosto.setEditable(false);
            return false;
        }
        
        if(jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se pudo buscar el nombre de un Evento, el campo Nombre está vacío."); 
            return false;
        }
        return true;
    }
    
    public boolean validarQueSePuedeGuardar(){
        
        if(!jTextFieldNombre.isEditable() || !jTextFieldCosto.isEditable()){
            jTextFieldNombre.setEditable(true);
            jTextFieldCosto.setEditable(true);
            return false;
        }
        
        if(!jTextFieldCosto.isEditable()){
            jTextFieldCosto.setEditable(true);
            return false;
        }
        
        if(jTextFieldID.isEditable()){
            jTextFieldID.setText("");
            jTextFieldID.setEditable(false);
            return false;
        }
        if(jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se pudo guardar evento, Falta el campo Nombre."); 
            return false;
        }
        
        if(jTextFieldCosto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se pudo guardar el evento, Falta el campo Costo."); 
            return false;
        }
        
        if(jComboBox1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "El campo Sucursal no ha sido seleccionado."); 
            return false;
        }
        
        try{
            int clause = Integer.parseInt(jTextFieldCosto.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No ha ingresado bien el valor monetario."); 
        }
        return true;
    }
    
    
    
    public void cargarSucursalesEnCbx(){
        ResultSet rs = eventosNegocio.retrieveSucursales();
        try {
            while (rs.next()) {
                jComboBox1.addItem(rs.getString(1));
            }
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
}
