/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_FlightSystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import negocio.InfoEventoN;


/**
 *
 * @author jossava
 * @author JONATHAN
 */
public class InfoEvento extends javax.swing.JFrame {

    
    InfoEventoN infoEvNegocio;
    ResultSet rs;
    
    MenuPrincipal mP;
    
    /**
     * Constructor
     */
    public InfoEvento(Connection conexion, MenuPrincipal mp) {
        initComponents();
        infoEvNegocio = new InfoEventoN(conexion);
        rs=null;
        
        mP = mp;
        
        this.setVisible(true);
        
        cargarInfoEnComboBoxes();
        limpiarCampos();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblubicaciones = new javax.swing.JLabel();
        jTextFieldTarifa = new javax.swing.JTextField();
        jTextFieldFechaI1 = new javax.swing.JTextField();
        jTextFieldFechaF1 = new javax.swing.JTextField();
        jTextFieldHoraI1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jComboBoxEventos = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxUbicaciones = new javax.swing.JComboBox<>();
        jTextFieldFechaI2 = new javax.swing.JTextField();
        jTextFieldFechaI3 = new javax.swing.JTextField();
        jTextFieldFechaF2 = new javax.swing.JTextField();
        jTextFieldFechaF3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldHoraI2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldHoraF2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldHoraF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblubicaciones.setFont(new java.awt.Font("L M Roman Demi10", 1, 48)); // NOI18N
        lblubicaciones.setForeground(new java.awt.Color(1, 1, 1));
        lblubicaciones.setText("Información del evento");

        jLabel3.setText("Fecha inicio:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre del evento", "Ubicacion", "Fecha inicio", "Fecha final", "Hora inicio", "Hora final", "Cover Asistentes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setText("Nombre del Evento");

        jLabel6.setText("Cover evento:");

        jLabel5.setText("Fecha final:");

        jLabel8.setText("Hora inicio:");

        jLabel9.setText("Hora final:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarbtnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarbtnAgregarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButtonAtras.setMaximumSize(new java.awt.Dimension(50, 40));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(50, 40));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(58, 34));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jComboBoxEventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - -" }));

        jLabel10.setText("Ubicacion");

        jComboBoxUbicaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - -" }));

        jLabel1.setText("Año");

        jLabel2.setText("Mes");

        jLabel7.setText("Día");

        jLabel11.setText("Año");

        jLabel12.setText("Mes");

        jLabel13.setText("Día");

        jLabel14.setText(":");

        jLabel15.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 145, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 445, Short.MAX_VALUE)
                        .addComponent(lblubicaciones)
                        .addGap(368, 368, 368))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTarifa)
                            .addComponent(jComboBoxUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel12)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel13)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldFechaI1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldFechaI2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldFechaI3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFechaF1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jTextFieldFechaF2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldFechaF3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldHoraI1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoraI2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoraF1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoraF2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblubicaciones)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaF2)
                            .addComponent(jTextFieldFechaF3)
                            .addComponent(jTextFieldFechaF1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaI3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaI1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaI2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHoraI1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHoraI2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHoraF1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHoraF2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarbtnBuscarActionPerformed
        if(validarQueSePuedeBuscar()){
                rs=infoEvNegocio.retrieve(jComboBoxEventos.getSelectedItem().toString());
                actualizarTabla(rs);
            
        }
    }//GEN-LAST:event_jButtonBuscarbtnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButtonAgregarbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarbtnAgregarActionPerformed
        String accion="insert";
        enviarPeticion(accion);
    }//GEN-LAST:event_jButtonAgregarbtnAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String nombreEvento = "";
        if(jComboBoxEventos.getSelectedIndex()!=0){
            nombreEvento = jComboBoxEventos.getSelectedItem().toString();
        }        
        limpiarCampos();
        
        if(nombreEvento.equals("")){
            JOptionPane.showMessageDialog(null, "Seleccione el nombre del evento del cual quiere eliminar la información.");

        }else{
            if(infoEvNegocio.delete(nombreEvento)){
                actualizar();
                JOptionPane.showMessageDialog(null, "Se ha eliminado la información del evento.");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo eliminar la información del evento.");
            }
        }
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String accion = "modify";
        enviarPeticion(accion);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        mP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxEventos;
    private javax.swing.JComboBox<String> jComboBoxUbicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFechaF1;
    private javax.swing.JTextField jTextFieldFechaF2;
    private javax.swing.JTextField jTextFieldFechaF3;
    private javax.swing.JTextField jTextFieldFechaI1;
    private javax.swing.JTextField jTextFieldFechaI2;
    private javax.swing.JTextField jTextFieldFechaI3;
    private javax.swing.JTextField jTextFieldHoraF1;
    private javax.swing.JTextField jTextFieldHoraF2;
    private javax.swing.JTextField jTextFieldHoraI1;
    private javax.swing.JTextField jTextFieldHoraI2;
    private javax.swing.JTextField jTextFieldTarifa;
    private javax.swing.JLabel lblubicaciones;
    // End of variables declaration//GEN-END:variables

    public void limpiarCampos() {
        jComboBoxEventos.setSelectedIndex(0);
        jComboBoxUbicaciones.setSelectedIndex(0);
        jTextFieldFechaI1.setText("");
        jTextFieldFechaI2.setText("");
        jTextFieldFechaI3.setText("");
        jTextFieldFechaF1.setText("");
        jTextFieldFechaF2.setText("");
        jTextFieldFechaF3.setText("");
        jTextFieldHoraI1.setText("");
        jTextFieldHoraI2.setText("");
        jTextFieldHoraF1.setText("");
        jTextFieldHoraF2.setText("");
        jTextFieldTarifa.setText("");
        
        jTextFieldFechaI1.setEditable(false);
        jTextFieldFechaI2.setEditable(false);
        jTextFieldFechaI3.setEditable(false);
        jTextFieldFechaF1.setEditable(false);
        jTextFieldFechaF2.setEditable(false);
        jTextFieldFechaF3.setEditable(false);
        jTextFieldHoraI1.setEditable(false);
        jTextFieldHoraI2.setEditable(false);
        jTextFieldHoraF1.setEditable(false);
        jTextFieldHoraF2.setEditable(false);
        jTextFieldTarifa.setEditable(false);
        
        
        
        actualizar();
    }
    
    public void actualizar(){
        rs=infoEvNegocio.getDataSet();
        actualizarTabla(rs);
    }
    
    public void actualizarTabla(ResultSet rs){
        try{
            cleanJTable();
            int i = 0;
            while (rs.next()) {
                jTable1.setValueAt(rs.getString(1), i, 0);
                jTable1.setValueAt(rs.getString(2), i, 1);    
                jTable1.setValueAt(rs.getString(3), i, 2);
                jTable1.setValueAt(rs.getString(4), i, 3);
                jTable1.setValueAt(rs.getString(5), i, 4);   
                jTable1.setValueAt(rs.getString(6), i, 5);   
                jTable1.setValueAt(rs.getString(7), i, 6);   
                i++;
            }
            if(i==0)
                JOptionPane.showMessageDialog(null, "No hay datos por mostrar."); 

        }catch(SQLException se) {
            se.printStackTrace();
        }
    }
    
    public void cleanJTable(){
        for(int i=0 ; i<jTable1.getRowCount() ; i++){
            for(int j=0 ; j<jTable1.getColumnCount() ; j++){
                jTable1.setValueAt("", i, j);
            }
        }
    }

    public boolean validarQueSePuedeBuscar(){
        jComboBoxUbicaciones.setSelectedIndex(0);
        if(jTextFieldFechaI1.isEditable()|| jTextFieldFechaI2.isEditable()||jTextFieldFechaI3.isEditable()||
            jTextFieldFechaF1.isEditable()|| jTextFieldFechaF2.isEditable()||jTextFieldFechaF3.isEditable()||
                jTextFieldHoraI1.isEditable() || jTextFieldHoraI2.isEditable() 
                || jTextFieldHoraF1.isEditable() || jTextFieldHoraF2.isEditable()
                || jTextFieldTarifa.isEditable()){
            jTextFieldFechaI1.setText("");
            jTextFieldFechaI2.setText("");
            jTextFieldFechaI3.setText("");
            jTextFieldFechaF1.setText("");
            jTextFieldFechaF2.setText("");
            jTextFieldFechaF3.setText("");
            jTextFieldHoraI1.setText("");
            jTextFieldHoraI2.setText("");
            jTextFieldHoraF1.setText("");
            jTextFieldHoraF2.setText("");
            jTextFieldTarifa.setText("");

            jTextFieldFechaI1.setEditable(false);
            jTextFieldFechaI2.setEditable(false);
            jTextFieldFechaI3.setEditable(false);
            jTextFieldFechaF1.setEditable(false);
            jTextFieldFechaF2.setEditable(false);
            jTextFieldFechaF3.setEditable(false);
            jTextFieldHoraI1.setEditable(false);
            jTextFieldHoraI2.setEditable(false);
            jTextFieldHoraF1.setEditable(false);
            jTextFieldHoraF2.setEditable(false);
            jTextFieldTarifa.setEditable(false);
            return false;
        }
        
        
        if(jComboBoxEventos.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "No se pudo encontrar el evento, "+'\n'
                                            + "el campo Nombre de evento no ha sido seleccionado."); 
            return false;
        }
        return true;
    }
    
    public boolean validarQueSePuedeGuardarOModificar(){
                        
        if(jTextFieldFechaI1.isEditable()&& jTextFieldFechaI2.isEditable() 
                && jTextFieldFechaF1.isEditable() && jTextFieldFechaF2.isEditable()
                && jTextFieldHoraI1.isEditable() && jTextFieldHoraI2.isEditable() 
                && jTextFieldHoraF1.isEditable() && jTextFieldHoraF2.isEditable()
                && jTextFieldTarifa.isEditable()){
            
            if(jComboBoxEventos.getSelectedIndex()==0 || jComboBoxUbicaciones.getSelectedIndex()==0
                || jTextFieldFechaI1.getText().equals("") || jTextFieldFechaI2.getText().equals("") || jTextFieldFechaI3.getText().equals("")
                || jTextFieldFechaF1.getText().equals("") || jTextFieldFechaF2.getText().equals("") || jTextFieldFechaF3.getText().equals("")
                || jTextFieldHoraI1.getText().equals("") || jTextFieldHoraI2.getText().equals("") 
                || jTextFieldHoraF1.getText().equals("") || jTextFieldHoraF2.getText().equals("")
                || jTextFieldTarifa.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Falta uno de los campos."); 
                return false;
            }
            int tarifa=-1;
            try{
                tarifa = Integer.parseInt(jTextFieldTarifa.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Datos en Cover evento incorrectos");            
            }
            return true;
        }else{
            jTextFieldFechaI1.setEditable(true);
            jTextFieldFechaI2.setEditable(true);
            jTextFieldFechaI3.setEditable(true);
            jTextFieldFechaF1.setEditable(true);
            jTextFieldFechaF2.setEditable(true);
            jTextFieldFechaF3.setEditable(true);
            jTextFieldHoraI1.setEditable(true);
            jTextFieldHoraI2.setEditable(true);
            jTextFieldHoraF1.setEditable(true);
            jTextFieldHoraF2.setEditable(true);
            jTextFieldTarifa.setEditable(true);
        }
        
        return false;
    }
    
    
    
    public void cargarInfoEnComboBoxes(){
        ResultSet rs = infoEvNegocio.retrieveNombreEvento();
        try {
            while (rs.next()) {
                jComboBoxEventos.addItem(rs.getString(1));
            }
        } catch (SQLException se) {
            se.printStackTrace();
        }
        rs = infoEvNegocio.retrieveUbicacion();
        try {
            while (rs.next()) {
                jComboBoxUbicaciones.addItem(rs.getString(1));
            }
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    
    public void enviarPeticion(String accion){
        if(validarQueSePuedeGuardarOModificar()){
            String nombreEvento = jComboBoxEventos.getSelectedItem().toString();
            String ubicacion = jComboBoxUbicaciones.getSelectedItem().toString();
            
            
            String fIni = jTextFieldFechaI1.getText() + "-" + jTextFieldFechaI2.getText() + 
                    "-" + jTextFieldFechaI3.getText();
            System.out.println(fIni);
            String fFin = jTextFieldFechaF1.getText() + "-" + jTextFieldFechaF2.getText() + 
                    "-" + jTextFieldFechaF3.getText();;
            String hIni = jTextFieldHoraI1.getText() + ":" + jTextFieldHoraI2.getText();
            String hFin = jTextFieldHoraF1.getText() + ":" + jTextFieldHoraF2.getText();
            String tarifa = jTextFieldTarifa.getText();

            if (infoEvNegocio.insertOrUpdate(nombreEvento, ubicacion, fIni, fFin, hIni, hFin, tarifa, accion)) {
                if(accion.equals("insert")){
                    JOptionPane.showMessageDialog(null, "Se ha insertado la información del evento.");
                }else if(accion.equals("modify")){
                    JOptionPane.showMessageDialog(null, "Se ha modificado la información del evento.");
                }

                limpiarCampos();
            }else{
                if(accion.equals("insert")){
                    JOptionPane.showMessageDialog(null, "No se pudo insertar la información del evento.");
                }else if(accion.equals("modify")){
                    JOptionPane.showMessageDialog(null, "No se pudo modificar  modificar la información del evento.");
                }
            }

            actualizar();
            
        }
    }

}
