/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_FlightSystem;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import negocio.LicitacionesN;

/**
 *
 * @author jossava
 */
public class Licitaciones extends javax.swing.JFrame {

    LicitacionesN ln;
    ResultSet rs;
    MenuPrincipal mP;
    
    /**
     * Creates new form Licitacion
     */
    public Licitaciones(Connection conexion, MenuPrincipal mP) {
        initComponents();
        ln = new LicitacionesN(conexion);
        rs = null;
        this.mP = mP;
        
        //limpiarCampos();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblubicaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNroL = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPersonal = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblubicaciones.setFont(new java.awt.Font("L M Roman Demi10", 1, 24)); // NOI18N
        lblubicaciones.setForeground(new java.awt.Color(1, 1, 1));
        lblubicaciones.setText("Licitación");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro licitación", "Contratista", "Sucursal", "Precio total", "Cantidad personal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("Id contratista:");

        jTextFieldNroL.setEditable(false);
        jTextFieldNroL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNroLActionPerformed(evt);
            }
        });

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio total:");

        jLabel5.setText("Id sucursal:");

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nro licitación:");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cantidad personal:");

        jTextFieldPersonal.setEditable(false);
        jTextFieldPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPersonalActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - -" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - -" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(58, 34));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(579, 579, 579)
                        .addComponent(lblubicaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNroL, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblubicaciones)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNroLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNroLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNroLActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTextFieldNroL.isEditable() && jTextFieldPrecio.isEditable() && jTextFieldPersonal.isEditable()){
            String id_evento=jTextFieldNroL.getText();
            String name = jTextFieldPrecio.getText();
            String costo = jTextFieldPersonal.getText();
            String suc = jComboBox1.getSelectedItem().toString();
            String contr = jComboBox2.getSelectedItem().toString();
            if(id_evento.equals("") || name.equals("") || costo.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan datos.");
                return;
            }
            if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Seleccione la Sucursal o Contratista");
                return;
            }
            if (ln.update(id_evento, contr, suc, name, costo)) {
                actualizar();
                JOptionPane.showMessageDialog(null, "Se ha modificado el Evento");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el Evento");
            }

        }else{
            jTextFieldNroL.setEditable(true);
            jTextFieldPrecio.setEditable(true);
            jTextFieldPersonal.setEditable(true);
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPersonalActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(jTextFieldNroL.isEditable() && !jTextFieldPrecio.isEditable() && !jTextFieldPersonal.isEditable()){
            String identificacion=jTextFieldNroL.getText();
            if(identificacion.equals("") ){
                JOptionPane.showMessageDialog(null, "No hay información del Evento por eliminar o faltan datos.");
                return;
            }else{
                if(ln.delete(identificacion)){
                    actualizar();
                    JOptionPane.showMessageDialog(null, "Se ha eliminado el Evento.");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el Evento."+'\n'
                        + "Puede estar intentando borrar un dato que no se puede eliminar"+'\n'
                        + "debido a que otro registro en otra tabla depende de él.");
                }
            }
        }else{
            jTextFieldNroL.setEditable(true);
            jTextFieldNroL.setText("");
            jTextFieldPersonal.setEditable(false);
            jTextFieldPrecio.setEditable(false);
        }    
}//GEN-LAST:event_jButton4ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
if(validarQueSePuedeBuscar()){
            if(!jTextFieldNroL.isEditable() && !jTextFieldPrecio.getText().equals("") && !jTextFieldPersonal.getText().equals("")){
                rs=ln.retrieve(jTextFieldNroL.getText());
                actualizarTabla(rs);
            }
        }// TODO add your handling code here:
}//GEN-LAST:event_jButtonBuscarActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(validarQueSePuedeGuardar()){
            String name = jTextFieldPrecio.getText();
            String costo = jTextFieldPersonal.getText();
            String suc = jComboBox1.getSelectedItem().toString();
            String cont = jComboBox1.getSelectedItem().toString();

            if (ln.insert(cont, suc, name, costo )) {
                JOptionPane.showMessageDialog(null, "Se ha insertado la información del Evento.");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo insertar la información del Evento.");
            }

            actualizar();
            limpiarCampos();
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        mP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldNroL;
    private javax.swing.JTextField jTextFieldPersonal;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JLabel lblubicaciones;
    // End of variables declaration//GEN-END:variables
    
    public void limpiarCampos() {
        jTextFieldNroL.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextFieldPrecio.setText("");
        jTextFieldPersonal.setText("");
        jTextFieldNroL.setEditable(false);
        jTextFieldPrecio.setEditable(false);
        jTextFieldPersonal.setEditable(false);
        actualizar();
}
    
    public void actualizar(){
        rs=ln.getDataSet();
        actualizarTabla(rs);
    }

    public void actualizarTabla(ResultSet rs){
        try{
            cleanJTable();
            int i = 0;
            while (rs.next()) {
                jTable2.setValueAt(rs.getString(1), i, 0);   
                jTable2.setValueAt(rs.getString(2), i, 1);                   
                jTable2.setValueAt(rs.getString(3), i, 2);
                jTable2.setValueAt(rs.getString(4), i, 3);
                jTable2.setValueAt(rs.getString(5), i, 4);
                i++;
            }
            if(i==0)
                JOptionPane.showMessageDialog(null, "No hay datos por mostrar."); 

        }catch(SQLException se) {
            se.printStackTrace();
        }
    }

    public void cleanJTable(){
        for(int i=0 ; i<jTable2.getRowCount() ; i++){
            for(int j=0 ; j<jTable2.getColumnCount() ; j++){
                jTable2.setValueAt("", i, j);
            }
        }
    }
    
    
    public void cargarSucursalesEnCbx(){
        ResultSet rs = ln.retrieveSucursales();
        try {
            while (rs.next()) {
                jComboBox1.addItem(rs.getString(1));
            }
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    public void cargarContratistasEnCbx(){
        ResultSet rs = ln.retrieveContratistas();
        try {
            while (rs.next()) {
                jComboBox2.addItem(rs.getString(1));
            }
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    public boolean validarQueSePuedeGuardar(){
        
        if(!jTextFieldPrecio.isEditable() || !jTextFieldPersonal.isEditable()){
            jTextFieldPrecio.setEditable(true);
            jTextFieldPersonal.setEditable(true);
            return false;
        }
        
        if(!jTextFieldPersonal.isEditable()){
            jTextFieldPersonal.setEditable(true);
            return false;
        }
        
        if(jTextFieldNroL.isEditable()){
            jTextFieldNroL.setText("");
            jTextFieldNroL.setEditable(false);
            return false;
        }
        if(jTextFieldPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se pudo guardar Licitacion, Falta el campo Precio."); 
            return false;
        }
        
        if(jTextFieldPersonal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se pudo guardar el Licitacion, Falta el campo Personal."); 
            return false;
        }
        
        if(jComboBox1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "El campo Sucursal no ha sido seleccionado."); 
            return false;
        }
        
        return true;
    }
    
    public boolean validarQueSePuedeBuscar(){
        jComboBox1.setSelectedIndex(0);
        if(!jTextFieldNroL.isEditable()){
            jTextFieldNroL.setText("");
            jTextFieldNroL.setEditable(true);
            return false;
        }
        if(!jTextFieldPrecio.isEditable() || jTextFieldPersonal.isEditable()){
            jTextFieldPrecio.setEditable(true);
            jTextFieldPersonal.setText("");
            jTextFieldPersonal.setEditable(false);
            return false;
        }
        
        if(jTextFieldPersonal.isEditable()){
            jTextFieldPersonal.setText("");
            jTextFieldPersonal.setEditable(false);
            return false;
        }
        
        return true;
    }


}

