/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_FlightSystem;

import javax.swing.JOptionPane;

/* Para detectar accion del textField:*/
import java.awt.event.ActionEvent;
/* Para detectar accion del passwordField:*/
import javax.swing.AbstractAction;
import javax.swing.Action;
/*Demás imports para la GUI*/
import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class Login extends javax.swing.JFrame {
    private Controller.FlightReservationSystem flightSystem;
    
    /**
        Constructor
    */
    public Login(Controller.FlightReservationSystem frs) {
        initComponents();
        
        flightSystem = frs;
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        accionDePasarAPassword(jTextFieldUserName);
        accionDeHundirBoton(jPasswordField1);
        this.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassWord = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabelBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Authentication");
        setName("frame"); // NOI18N

        jPanel1.setLayout(null);

        jLabelUser.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("Username");
        jPanel1.add(jLabelUser);
        jLabelUser.setBounds(420, 180, 120, 29);

        jLabelPassWord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPassWord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassWord.setText("Password");
        jPanel1.add(jLabelPassWord);
        jLabelPassWord.setBounds(420, 220, 130, 29);
        jPanel1.add(jTextFieldUserName);
        jTextFieldUserName.setBounds(590, 180, 180, 30);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(590, 220, 180, 30);

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);
        jButtonLogin.setBounds(620, 270, 120, 30);

        jButtonExit.setText("Salir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit);
        jButtonExit.setBounds(620, 350, 120, 30);

        jButtonRegister.setText("Registrarse");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegister);
        jButtonRegister.setBounds(620, 310, 120, 30);

        lblBienvenida.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        lblBienvenida.setText("BIENVENIDO");
        jPanel1.add(lblBienvenida);
        lblBienvenida.setBounds(270, 30, 350, 60);

        lblTitle.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        lblTitle.setText("SISTEMA DE RESERVA DE VUELOS");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(270, 100, 820, 58);

        jLabelBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/airbusFrontal.jpg"))); // NOI18N
        jLabelBackGround.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelBackGround.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel1.add(jLabelBackGround);
        jLabelBackGround.setBounds(0, 10, 1350, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1332, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String un = jTextFieldUserName.getText();
        String pw = jPasswordField1.getText();
        if(un.equals("") || pw.equals("")){
            JOptionPane.showMessageDialog(jPanel1, 
                    "Nombre de Usuario o password vacíos",
                "Authentication Error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(flightSystem.validateUser(un, pw)){
            JOptionPane.showMessageDialog(jPanel1,"Bienvenido a nuestro sistema\n"
                    + "Servicios que ofrecemos :\n"
                    + "Consulta de Vuelos\n"
                    + "Reserva de Vuelos\n"
                    + "Información del estado de los vuelos.\n"
                    + "\nDisfrute de la experiencia. Estamos para ayudarle",
                "Servicios Ofrecidos", JOptionPane.INFORMATION_MESSAGE); 
            flightSystem.createMenuPpal();
            this.cleanData();
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(jPanel1, 
                    "Nombre de Usuario o password inválido",
                "Authentication Error", JOptionPane.ERROR_MESSAGE); 
            return;
        }
        
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        flightSystem.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        flightSystem.createRegistration();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    
    
    /* Método para pasar del username a pw con solo un enter    */ 
    private void accionDePasarAPassword(JTextField jTxtF1) {
        jTextFieldUserName.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jPasswordField1.requestFocusInWindow();    
                }
            });
    }
    
    /*
    Método para detectar cuando la tecla intro es presionada en el passwordfield, 
    es como si el usuario presionara el botón login
    */
    private void accionDeHundirBoton(JPasswordField jp){
        
        Action action = new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                jButtonLoginActionPerformed(e);
            }
        };
        jp.addActionListener(action);
    }
    
    public void visible(boolean bool) {
        this.setVisible(bool);
    }
    
    private void cleanData() {
        this.jTextFieldUserName.setText("");
        this.jPasswordField1.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabelBackGround;
    private javax.swing.JLabel jLabelPassWord;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
