/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_FlightSystem;

import javax.swing.JOptionPane;

/* Para detectar accion del textField:*/
import java.awt.event.ActionEvent;
/* Para detectar accion del passwordField:*/
import javax.swing.AbstractAction;
import javax.swing.Action;
/*Demás imports para la GUI*/
import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class Login extends javax.swing.JFrame {
    private Controller.FlightReservationSystem flightSystem;
    
    /**
        Constructor
    */
    public Login(Controller.FlightReservationSystem frs) {
        initComponents();
        
        flightSystem = frs;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        accionDePasarAPassword(jTextField1);
        accionDeHundirBoton(jPasswordField1);
        this.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Authentication");
        setName("frame"); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 180, 120, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 220, 130, 29);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(590, 180, 180, 30);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(590, 220, 180, 30);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 270, 90, 30);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(630, 350, 90, 30);

        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 310, 90, 30);

        lblTitle.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        lblTitle.setText("BIENVENIDO");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(270, 30, 350, 60);

        lblTitle1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        lblTitle1.setText("SISTEMA DE RESERVA DE VUELOS");
        jPanel1.add(lblTitle1);
        lblTitle1.setBounds(270, 100, 820, 58);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/airbusFrontal.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 0, 1350, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String un = jTextField1.getText();
        String pw = jPasswordField1.getText();
        if(un.equals("") || pw.equals("")){
            JOptionPane.showMessageDialog(jPanel1, "Nombre de Usuario o password vacíos",
                "Authentication Error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(flightSystem.validateUser(un, pw)){
            flightSystem.createMenuPpal();
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Nombre de Usuario o password inválido",
                "Authentication Error", JOptionPane.ERROR_MESSAGE); 
            return;
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        flightSystem.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        flightSystem.createRegistration();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    /* Método para pasar del username a pw con solo un enter    */ 
    private void accionDePasarAPassword(JTextField jTxtF1) {
        jTextField1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jPasswordField1.requestFocusInWindow();    
                }
            });
        
        
    }
    
    /*
    Método para detectar cuando la tecla intro es presionada en el passwordfield, 
    es como si el usuario presionara el botón login
    */
    private void accionDeHundirBoton(JPasswordField jp){
        
        Action action = new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                jButton1ActionPerformed(e);
            }
        };
        jp.addActionListener(action);
    }
    
    public void visible(boolean bool) {
        this.setVisible(bool);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables

    

    
}
